#!/usr/bin/env python


from __future__ import print_function
from __future__ import unicode_literals

import os
import sys


from js.parser import parse
from js.bytecode import dis
from js.compiler import compile_ast


args = iter(sys.argv)
next(args)  # program name

arg = next(args, None)
if arg in (None, "-"):
    source = sys.stdin.read()
elif os.path.exists(arg):
    source = open(arg, "r").read()
else:
    source = arg

print("Source:")
for i, line in enumerate(source.split("\n")):
    print("{line:>3} {text}".format(line=(i + 1), text=line))
print()

bc = compile_ast(parse(source))

print("Bytecode:")
print(dis(bc.code))
print()

print("Functions:")
for i, func in enumerate(bc.constants_fn):
    print(" {0}:".format(i))
    print(dis(func.code))
